---
apiVersion: apps/v2
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: sync-strategies
        image: docker.io/kostiscodefresh/gitops-simple-app:v2
        ports:
        - containerPort: 8080
